mysite/website/users/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, EmailField, PasswordField, SubmitField, BooleanField, ValidationError,SelectField
from wtforms.validators import DataRequired, Email, EqualTo, NumberRange, Length

from website import bcrypt
from website.models import User
from pycountry import countries

country_names = [c.name for c in countries]
country_names.sort()


class SignUp(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired()])
    age = IntegerField('Age', validators=[DataRequired(), NumberRange(min=13, max=99)], default=13)
    phone = StringField('Phone', validators=[DataRequired()])
    country = SelectField('Country', validators=[DataRequired()], choices=country_names, default=country_names[0])
    address = StringField('Address', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField(
        'Confirm Password',
        validators=[DataRequired(),
                    EqualTo('password', 'Passwords are not equal.')])
    remember = BooleanField('Remember me')
    submit = SubmitField('Sign up')

    def validate_email(self, email):
        email = User.query.filter_by(email=email.data).first()
        if email:
            raise ValidationError('This email is already in use! Please choose another one.')


class Login(FlaskForm):
    email = EmailField('Email', validators=[DataRequired('Please provide an email.'), Email()])
    password = PasswordField('Password', validators=[DataRequired('Please put in your password')])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')


class UpdateEmail(FlaskForm):
    email = EmailField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Update Email')

    def validate_email(self, email):
        email = User.query.filter_by(email=email.data).first()
        if email:
            raise ValidationError('This email is already in use! Please use another one.')


class UpdatePassword(FlaskForm):
    current_password = PasswordField('Current Password', validators=[DataRequired()])
    new_password = PasswordField('New Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm New Password', validators=[DataRequired(), EqualTo('new_password')])
    submit = SubmitField('Update Password')

    # def validate_current_password(self, current_password):
    #     password = User.query.filter_by(email=current_user.email,
    #                                     password=bcrypt.generate_password_hash(current_password.data)).first()
    #     if not password:
    #         raise ValidationError('Current password is incorrect!')

    def validate_new_password(self, new_password):
        if self.current_password.data == new_password.data:
            raise ValidationError('New password cannot be the same as the old password!')

# class deleteProfile(FlaskForm):
    

mysite/website/main/routes.py
from flask import Blueprint, render_template, request
from flask_login import current_user

from website.models import ComicBook, Cart, Library, WishList

main = Blueprint('main', __name__)


# The home page route
@main.route('/')
def home():
    top_picks = ComicBook.query.filter_by(top_pick=True).all()[:6]
    kadoko_list = ComicBook.query.filter_by(category_query='kadoko').all()[:6]
    latest = ComicBook.query.all()[-1:-7:-1]
    free = ComicBook.query.filter_by(price=-1).all()
    return render_template('main/home.html', title='Home', top_picks=top_picks,
                           kadoko_list=kadoko_list, latest=latest, freebies=free)


@main.route('/about')
def about():
    return render_template('main/about.html', title='About us')


@main.route('/comics')
def comics():
    comic_list = {
        'action': ComicBook.query.filter_by(category_query='action').all()[0:6],
        'jabulani': ComicBook.query.filter_by(category_query='jabulani').all()[0:6],
        'horror': ComicBook.query.filter_by(category_query="horror").all()[0:6],
        'comedy': ComicBook.query.filter_by(category_query='comedy').all()[0:6],
        'fantasy': ComicBook.query.filter_by(category_query='fantasy').all()[0:6],
        'romance': ComicBook.query.filter_by(category_query='romance').all()[0:6],
    }

    return render_template('main/comics.html', title='Comics', comics=comic_list)


@main.route('/comic-category/<category_query>')
def comic_category(category_query):
    page = request.args.get('page', 1, type=int)
    category_list = ComicBook.query.filter_by(category_query=category_query).paginate(page=page, per_page=8)

    left_over = len(category_list.items)
    rows = 1
    if left_over > 4:
        rows = 2
    return render_template('/main/category_info.html', title=category_list.items[0].category,
                           comics=category_list, len=len, rows=rows, left_over=left_over)


@main.route('/comic-info/<title_query>', methods=['GET', 'POST'])
def comic_info(title_query):
    # Get the book
    book = ComicBook.query.filter_by(title_query=title_query).first()

    if book is None:
        return "Book not found", 404  # Handle the case where the book is not found

    if current_user.is_authenticated:
        # Use foreign keys directly
        book_in_cart = Cart.query.filter_by(book_id=book.id, user_id=current_user.id).first()
        book_in_lib = Library.query.filter_by(book_id=book.id, user_id=current_user.id).first()
        book_in_wishlist = WishList.query.filter_by(book_id=book.id, user_id=current_user.id).first()
    else:
        book_in_cart = None
        book_in_lib = None
        book_in_wishlist = None

    return render_template('main/comic_info.html', title='Comics info', book=book,
                           in_wishlist=book_in_wishlist is not None,
                           in_lib=book_in_lib is not None, in_cart=book_in_cart is not None)


@main.route('/top-picks')
def top_picks():
    page = request.args.get('page', 1, type=int)
    top_picks_list = ComicBook.query.filter_by(top_pick=True).paginate(page=page, per_page=8)

    left_over = len(top_picks_list.items)
    rows = 1
    if left_over > 4:
        rows = 2

    return render_template('main/recommended.html', title='Top Picks', comics=top_picks_list, len=len,
                           rows=rows, left_over=left_over)
    
    
@main.route("/search")
def search():
    search_query = request.args.get("q")
    all_comics = ComicBook.query.all()
    title_list = [comic for comic in all_comics if search_query.lower() in comic.title.lower()]
    category_list = [comic for comic in all_comics if search_query.lower() in comic.category.lower()]
    author_list = [comic for comic in all_comics if search_query.lower() in comic.author.lower()]
    length = 1
    
    if len(title_list) == len(category_list) == len(author_list) == 0:
        length = 0
            
    return render_template("main/search.html", title=f"Search for\"{search_query}\"", search_query=search_query, all_comics=all_comics, length=length)
    

@main.route('/watch')
def series():
    return render_template('main/series.html', title='Watch Series')

mysite/website/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request,Flask, render_template,send_file,Response
from flask_login import current_user, login_user, logout_user, login_required
import matplotlib.pyplot as plt
import base64
from io import BytesIO
from PIL import Image
from reportlab.pdfgen import canvas
from wtforms import StringField
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
from website import bcrypt, db
from website.models import User, Cart, Library, CardDetails, WishList, ComicBook
from wtforms.validators import DataRequired
from website.users.forms import SignUp, Login, UpdatePassword, UpdateEmail

# Blueprint
users = Blueprint('users', __name__)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = SignUp()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            flash('Email is already registered. Please log in or use a different email.', 'danger')
            return redirect(url_for('users.signup'))
        
        existing_phone = User.query.filter_by(phone=form.phone.data).first()
        if existing_phone:
            flash('Phone number is already registered. Please log in or use a different number.', 'danger')
            return redirect(url_for('users.signup'))
        
        first_name = form.first_name.data
        last_name = form.last_name.data
        email = form.email.data
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        phone = form.phone.data
        age = form.age.data
        country = form.country.data
        address = form.address.data
 
        name_query = (first_name + '-' + last_name).replace(' - ', '-').replace(':', '').replace('\'', '').replace(' ', '-').lower()
        user_num = len(User.query.all()) + 1

        user = User(first_name=first_name, last_name=last_name, email=email, password=password, phone=phone,age=age, country=country, address= address)
        
        db.session.add(user)
        db.session.commit()
        login_user(user, remember=form.remember.data)
        flash('Account created successfully', 'success')
        return redirect(url_for('main.home'))

    return render_template('user/signup.html', title='Sign up', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = Login()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Login successful', 'success')
            prev = request.args.get('next')
            if prev:
                return redirect(prev)
            return redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Incorrect email or password!', 'danger')
            return redirect(url_for('users.login'))
    return render_template('user/login.html', title='Login', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    cards = CardDetails.query.filter_by(owner=current_user).all()
    amount = len(Library.query.filter_by(bought_by=current_user).all())
    return render_template('user/account_settings.html', title='Account', cards=cards, number=len(cards), amount=amount)


@users.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('main.home'))
    else:
        return redirect(url_for('main.home'))


@users.route('/account/update-email', methods=['GET', 'POST'])
@login_required
def update_email():
    form = UpdateEmail()
    if request.method == 'GET':
        form.email.data = current_user.email
    elif form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        user.email = form.email.data
        db.session.commit()
        flash('Your email has been updated!', 'success')
        return redirect(url_for('users.account'))
    return render_template('user/update_email.html', title='Account', form=form)


@users.route('/account/update-password', methods=['GET', 'POST'])
@login_required
def update_password():
    form = UpdatePassword()

    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if bcrypt.check_password_hash(user.password, form.current_password.data):
            user.password = bcrypt.generate_password_hash(form.new_password.data)
            db.session.commit()
            flash('Your password has been updated!', 'success')
            return redirect(url_for('users.account'))
        else:
            flash('Your current password is incorrect.', 'danger')
    return render_template('user/update_password.html', title='Account', form=form)


@users.route('/cart')
@login_required
def cart():
    cart_list = Cart.query.filter_by(buyer=current_user).all()
    quantity = request.form.getlist("quantity")
    print(quantity)
    total = sum(comic.comic_book.price for comic in cart_list)
    return render_template('user/cart.html', title='Cart', items=cart_list, length=len(cart_list), total=total)


@users.route('/wishlist')
@login_required
def wishlist():
    wish_list = WishList.query.filter_by(buyer=current_user).all()
    in_cart = Cart.query.filter_by(buyer=current_user).first()
    return render_template('user/wishlist.html', title='Cart', items=wish_list, length=len(wish_list), in_cart=in_cart is not None)


@users.route('/library')
@login_required
def library():
    page = request.args.get('page', 1, type=int)
    library_items = Library.query.filter_by(bought_by=current_user).paginate(page=page, per_page=8)
    return render_template('user/library.html', title='Library', items=library_items, length=library_items.total, len=len)
   
@users.route("/report")
@login_required
def report():
    sort_order = request.args.get('sort_order', 'none')
    
    if sort_order == 'asc':
        top_picks_list = ComicBook.query.order_by(ComicBook.stock_quantity.asc()).limit(10).all()
        report_pdf_path = "mysite/website/static/report/asc_report.pdf"
    elif sort_order == 'desc':
        top_picks_list = ComicBook.query.order_by(ComicBook.stock_quantity.desc()).limit(10).all()
        report_pdf_path = "mysite/website/static/report/desc_report.pdf"
    else:
        top_picks_list = ComicBook.query.limit(10).all()
        report_pdf_path = "mysite/website/static/report/unsorted_report.pdf"
    
    library = Library.query.filter_by(bought_by=current_user).all()
  
    plt.figure(figsize=(11, 9))
    plt.bar([comic.title for comic in top_picks_list], [comic.stock_quantity for comic in top_picks_list])
    plt.xlabel('Comic Book')
    plt.ylabel('Stock Quantity')
    plt.title('Top 10 Comics by Stock Quantity')
    plt.xticks(rotation=45, ha="right")
    
    report_image_path = "mysite/website/static/images/stock_quantity.png"
    plt.savefig(report_image_path)
  
    c = canvas.Canvas(report_pdf_path, pagesize=(800, 600))
    c.drawImage(report_image_path, 100, 40, 600)
    c.save()
    
    comics = [(comic.title, comic.stock_quantity) for comic in top_picks_list]
    
    return render_template("user/report.html", title="Report", comics=comics, library=library)

@users.route('/report/download')
@login_required
def download_pdf():
    sort_order = request.args.get('sort_order', 'none')
    
    if sort_order == 'asc':
        file_path = "static/report/asc_report.pdf"
    elif sort_order == 'desc':
        file_path = "static/report/desc_report.pdf"
    else:
        file_path = "static/report/unsorted_report.pdf"
    
    return send_file(file_path, as_attachment=True, mimetype="application/pdf", download_name="report.pdf")


@users.route("/report-income")
@login_required
def report_income():
    period = request.args.get('period', 'annual')  # Default
    top_picks_list = ComicBook.query.all()
    
    # Calculate income based on the selected period
    income_values = []
    if period == 'quarterly':
        income_values = [comic.price * comic.stock_quantity / 4 for comic in top_picks_list]
    elif period == 'biannual':
        income_values = [comic.price * comic.stock_quantity / 2 for comic in top_picks_list]
    else:  
        income_values = [comic.price * comic.stock_quantity for comic in top_picks_list]
    
    
    comic_titles = [comic.title for comic in top_picks_list]

    plt.figure(figsize=(11, 9))
    plt.bar(comic_titles[:10], income_values[:10])
    plt.xlabel('Comic Book')
    plt.ylabel('Total Income (R)')
    plt.title(f'Total Income per Comic Book ({period.capitalize()})')
    
    plt.xticks(rotation=45, ha="right")
    plot_path = f"mysite/website/static/images/stock_income_{period}.png"
    pdf_path = f"mysite/website/static/report_income/report_{period}.pdf"
    
    plt.savefig(plot_path)
    
    try:
        c = canvas.Canvas(pdf_path, pagesize=(800, 600))
        c.drawImage(plot_path, 100, 40, 600)
        c.save()
    except Exception as e:
        return f"Error generating report: {str(e)}", 500
    
    # Prepare comics data for the template
    comics = [(comic.title, income) for comic, income in zip(top_picks_list, income_values)]
    comics = comics[:10]
    
    return render_template(
        "user/report_income.html",title="Report",comics=comics,period=period)

@users.route('/report-income/report_income.pdf')
@login_required
def download_income_pdf():
    period = request.args.get('period', 'annual')  # Default 
    return send_file(
        f"static/report_income/report_{period}.pdf",
        as_attachment=True,
        mimetype="pdf",
        download_name=f"report_income_{period}.pdf"
    )

mysite/website/templates/user/account_settings.html
{% extends "base.html" %}
{% block styles %}
<style>
    .card {
        background-color: rgb(77, 77, 86);
        color: #eee;
        width: 15rem; 
        min-width: 220px;
    }
</style>
{% endblock styles %}

{% block content %}
<section class="p-3">
    <div class="container-md mt-md-3 mb-md-3" style="max-width: 1048px;">
        <h2 class="h2 mt-3 mb-3">Account Settings</h2>
        <hr style="height: 4px;">
        <div class="row row-cols-1 row-cols-md-2">
            <div class="col-md-8">
                <h3 class="h3">Info</h3>
                <p class="row">
                    <span class="col-3 col-md-5">Email:</span>
                    <span class="col-9 col-md-7">{{ current_user.email }}</span>
                </p>
                <p class="row">
                    <span class="col-3 col-md-5">Country:</span>
                    <span class="col-9 col-md-7">{{ current_user.country }}</span>
                </p>
                <p class="row">
                    <span class="col-3 col-md-5">Age:</span>
                    <span class="col-9 col-md-7">{{ current_user.age }}</span>
                </p>
                <p class="row">
                    <span class="col-3 col-md-5">Books in library:</span>
                    <span class="col-9 col-md-7">{{ amount }}</span>
                </p>
                <p class="row">
                    <span class="col-3 col-md-5">Date joined:</span>
                    <span class="col-9 col-md-7">{{ current_user.date_joined }}</span>
                </p>
            </div>
            <div class="col-md-4 mt-3">
                <!-- <h3 class="h3">Update info</h3> -->
                <a href="{{ url_for('users.update_email') }}" class="btn btn-primary">Update email</a>
                <br><br>
                <a href="#" class="btn btn-primary">Change country</a>
                <br><br>
                <a href="{{ url_for('users.update_password') }}" class="btn btn-primary">Update password</a>
                <br><br>
            </div>
        </div>

        <div class="col mt-5">
            <h3 class="h3">Cards</h3>
            <div class="row row-cols-1 row-cols-md-3">
                {% for card in cards %}
                    <div class="card mb-3 me-3 p-1">
                        <img src="{{ url_for('static', filename='images/card_images/' + card.card_brand +'_thumb.png' ) }}" class="img-fluid img-card-top" alt="Comic Book Cover">
                        <div class="card-body pt-3">
                            <p class="fs-6 m-0 pb-3">Card ending in **{{ card.card_number[-1: -5: -1] }}</p>
                            <hr style="width: 98%; color: #eee; height: 4px; margin: 2px;">
                            <!-- Modal button -->
                            <button type="button" class="btn btn-danger mt-1 mb-0 ms-auto" data-bs-toggle="modal" data-bs-target="#removeCardModal">
                                Remove Payment method
                            </button>
                        </div>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="removeCardModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Remove payment method</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to remove this payment method?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <form action="{{ url_for('action.delete_payment_method', card_number=card.card_number, next=request.url) }}" method="POST">
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                        </div>
                    </div>
                {% endfor %}
            {% if number <= 2 %}
                <a href="{{ url_for('others.add_card_details') }}" class="mt-auto mb-auto ms-5 btn btn-primary" style="max-width: 130px">Add payment method</a>
            {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

mysite/website/templates/user/cart.html
{% extends "base.html" %}
{% block styles %}
<style>
    .card {
        background-color: rgb(120, 120, 120, 0.2) !important;
        color: var(--primary-text-colour);
        border: none !important;
        border-radius: 5px;
    }

    .card img {
        align-self: start;
        max-height: 220px;
    }

    .img-div {
        padding: 0;
    }

    .cancel-button {
        display: grid;
        align-self: center;
    }

    .card-body {
        padding: 0 1rem;
        display: grid;
        align-self: center;
    }

    @media screen and (max-width: 576px) {
        .cover {
            padding-top: 0.5rem;
        }
        .cancel-button {
            display: grid;
            align-self: flex-end;
            padding: 0 1rem;
            padding-bottom: 0.5rem;
        }
    }
</style>
{% endblock styles %}

{% block content %}
<section>
    <div class="container-md mt-4 mb-4" style="max-width: 1048px;">
        <div class="d-flex">
            <h3 class="h2 me-auto"><i class="bi bi-cart4" style="font-size: 30px;"></i> Cart</h3>
            {% if length > 0 %}
            <a href="{{ url_for('others.checkout') }}" class="btn btn-primary ms-auto mt-auto mb-auto">Check out</a>
            {% endif %}
        </div>
        <hr style="height: 4px;">
        <div class="ps-2" style="min-height: 360px;">
            {% if length == 0 %}
                <p>Cart empty. Lets add some items <a href="{{ url_for('main.comics') }}" style="cursor: pointer;">Take me back.</a></p>
            {% else %}
                <!-- The description display -->
                <div class="max-width row d-sm-flex d-none">
                    <p class="col-1 fs-5 fw-light">
        
                    </p>
                    <p class="col-4 fs-5 fw-light">
                        TITLE
                    </p>
                    <p class="col-2 fs-5 fw-light">
                        CATEGORY
                    </p>
                    <p class="col-2 fs-5 fw-light">
                        PRICE
                    </p>
                    <p class="col-2 fs-5 fw-light">
                        QUANTITY
                    </p>
                    <p class="col-1 fs-5 fw-light">
                        
                    </p>

                </div>
                <!-- Display the cart items -->
                {% for comic in items %}
                    <div class="card mb-3 me-auto border p-1 ms-auto me-auto">
                        <div class="row row-cols-1 row-cols-sm-4 g-0" >
                            <div class="img-div col-sm-1">
                                <a href="{{ url_for('main.comic_info', title_query=comic.comic_book.title_query) }}">
                                    <img src="{{ url_for('static', filename='images/comic_images/'+comic.comic_book.filename) }}" alt="Comic Book Cover" style="max-width: 60px;">
                                </a>
                            </div>
                            <div class="col-sm-4 card-body d-flex">
                                <p class="m-0 fw-light ">{{ comic.comic_book.title }}</p>
                            </div>
                            <div class="col-sm-2 card-body d-flex">
                                <p class="m-0 fw-light">{{ comic.comic_book.category }}</p>
                            </div>
                            <div class="col-sm-2 card-body d-flex">
                                <p class="m-0 fw-light" id="price" name="">R {{ comic.comic_book.price * comic.quantity }}0</p>
                            </div>
                            <div class="col-sm-2 card-body d-flex">
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    {% if comic.quantity > 1 %}
                                        <a class="btn btn-primary" href="{{ url_for('action.update_quantity', title_query=comic.comic_book.title_query, count=-1, next=request.url) }}">-</a>
                                    {% else %}
                                        <a class="btn btn-primary disabled" href="#">-</a>
                                    {% endif %}
                                    <button class="btn btn-primary">{{ comic.quantity }}</button>
                                    {% if comic.quantity < 2 or comic.quantity <= comic.comic_book.stock_quantity %}
                                        <a class="btn btn-primary" href="{{ url_for('action.update_quantity', title_query=comic.comic_book.title_query, count=1, next=request.url) }}">+</a>
                                    {% else %}
                                        <a class="btn btn-primary disabled" href="#">+</a>
                                    {% endif %}
                                </div>
                            </div>
                            
                            <div class="col-sm-1 cancel-button justify-content-sm-center">
                                <form action="{{ url_for('action.remove_from_cart', title_query=comic.comic_book.title_query, next=request.url) }}" method="POST">
                                    <button type="submit" class="btn btn-outline-secondary"
                                            data-bs-toggle="tooltip" data-bs-placement="top"
                                            data-bs-custom-class="custom-tooltip"
                                            data-bs-title="Remove from cart">
                                        <i class="bi bi-x-square-fill"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</section>

<script>
    let price = document.getElementById("price")
    let selectElement = document.querySelector('#quantity');
</script>
{% endblock %}

mysite/website/templates/user/report.html
{% extends "base.html" %}
{% block styles %}
<style>
    .card {
        background-color: rgba(120, 120, 120, 0) !important;
        color: var(--primary-text-colour);
        border-left: 5px solid;
        border-right: 5px solid;
        border-radius: 0;
    }

    .card img {
        margin: auto;
    }

    .img-div {
        padding: 0;
    }

    .card-body {
        padding: 0 1rem;
        display: grid;
        align-self: center;
    }

    .form-container {
        display: flex;
        align-items: center;
        gap: 1rem;
    }

    .form-label {
        margin-bottom: 0;
    }

    .form-select {
        width: auto;
        max-width: 200px;
    }

    .form-btn {
        height: 2.5rem;
    }

    @media screen and (max-width: 576px) {
        .cover {
            padding-top: 0.5rem;
        }
        .cancel-button {
            display: grid;
            align-self: flex-end;
            padding: 0 1rem;
            padding-bottom: 0.5rem;
        }
    }
</style>
{% endblock styles %}

{% block content %}
<section>
    <div class="container-md mt-4 mb-4" style="max-width: 1048px;">
        <p class="h1 mb-sm-5">Top 10 Comics</p>
        
        <!-- Sorting Form -->
        <form action="{{ url_for('users.report') }}" method="GET" class="mb-4 form-container">
            <label for="sort_order" class="form-label">Sort By:</label>
            <select name="sort_order" id="sort_order" class="form-select">
                <option value="none" {% if request.args.get('sort_order') == 'none' %}selected{% endif %}>Unsorted</option>
                <option value="asc" {% if request.args.get('sort_order') == 'asc' %}selected{% endif %}>Ascending</option>
                <option value="desc" {% if request.args.get('sort_order') == 'desc' %}selected{% endif %}>Descending</option>
            </select>
            <button type="submit" class="btn btn-primary form-btn">Generate Report</button>
        </form>

        <div class="container">
            {% if comics %}
                {% for comic, stock_quantity in comics %}
                    <div class="card mb-3 me-auto border p-1 ms-auto me-auto">
                        <div class="row row-cols-1 row-cols-sm-2 g-0">
                            <div class="col-sm-6 card-body d-flex">
                                <p class="m-0 fs-5 fw-light">Comic Title: {{ comic }}</p>
                            </div>
                            <div class="col-sm-6 card-body d-flex">
                                <p class="fs-5 m-0 fw-light">Stock Quantity: {{ stock_quantity }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No comics data available to display.</p>
            {% endif %}
        </div>

        <!-- Matplotlib Plot Integration -->
        <div class="container mt-4">
            <h2>Top 10 Products by Stock Quantity</h2>
            <img src="{{ url_for('static', filename='images/stock_quantity.png') }}" alt="Stock Quantity Plot" />
            <a href="{{ url_for('users.download_pdf', sort_order=request.args.get('sort_order', 'none')) }}" class="btn btn-primary mt-3">Download PDF</a>
        </div>
    </div>
</section>
{% endblock %}