mysite/website/supplier/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField, SubmitField, BooleanField, IntegerField, DateField, PasswordField, SelectField
from wtforms.validators import DataRequired, Length, Email

from pycountry import countries

country_names = [c.name for c in countries]
country_names.sort()

class AddComic(FlaskForm):
    cover_image = FileField('Book cover', validators=[FileAllowed(['jpg', 'png']), DataRequired()])
    category = StringField('Category', validators=[DataRequired()])
    title = StringField('Title', validators=[DataRequired()])
    author = StringField('Author', validators=[DataRequired()])
    illustrator = StringField('Illustrator', validators=[DataRequired()])
    price = IntegerField('Price', validators=[DataRequired()], default=0)
    date = DateField('Date', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired(), Length(max=300)])
    stock_quantity = IntegerField('Stock Quantity', validators=[DataRequired()])
    top_pick = BooleanField('Best seller')
    submit = SubmitField('Add Book')


class AddFreelancer(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    phone = StringField('Phone', validators=[DataRequired()])
    address = StringField('Address', validators=[DataRequired()])
    country = SelectField('Country', validators=[DataRequired()], choices=country_names, default=country_names[0])
    submit = SubmitField('Add Freelancer')

mysite/website/main/routes.py
from flask import Blueprint, render_template, request
from flask_login import current_user

from website.models import ComicBook, Cart, Library, WishList

main = Blueprint('main', __name__)


# The home page route
@main.route('/')
def home():
    top_picks = ComicBook.query.filter_by(top_pick=True).all()[:6]
    kadoko_list = ComicBook.query.filter_by(category_query='kadoko').all()[:6]
    latest = ComicBook.query.all()[-1:-7:-1]
    free = ComicBook.query.filter_by(price=-1).all()
    return render_template('main/home.html', title='Home', top_picks=top_picks,
                           kadoko_list=kadoko_list, latest=latest, freebies=free)


@main.route('/about')
def about():
    return render_template('main/about.html', title='About us')


@main.route('/comics')
def comics():
    comic_list = {
        'action': ComicBook.query.filter_by(category_query='action').all()[0:6],
        'jabulani': ComicBook.query.filter_by(category_query='jabulani').all()[0:6],
        'horror': ComicBook.query.filter_by(category_query="horror").all()[0:6],
        'comedy': ComicBook.query.filter_by(category_query='comedy').all()[0:6],
        'fantasy': ComicBook.query.filter_by(category_query='fantasy').all()[0:6],
        'romance': ComicBook.query.filter_by(category_query='romance').all()[0:6],
    }

    return render_template('main/comics.html', title='Comics', comics=comic_list)


@main.route('/comic-category/<category_query>')
def comic_category(category_query):
    page = request.args.get('page', 1, type=int)
    category_list = ComicBook.query.filter_by(category_query=category_query).paginate(page=page, per_page=8)

    left_over = len(category_list.items)
    rows = 1
    if left_over > 4:
        rows = 2
    return render_template('/main/category_info.html', title=category_list.items[0].category,
                           comics=category_list, len=len, rows=rows, left_over=left_over)


@main.route('/comic-info/<title_query>', methods=['GET', 'POST'])
def comic_info(title_query):
    # Get the book
    book = ComicBook.query.filter_by(title_query=title_query).first()

    if book is None:
        return "Book not found", 404  # Handle the case where the book is not found

    if current_user.is_authenticated:
        # Use foreign keys directly
        book_in_cart = Cart.query.filter_by(book_id=book.id, user_id=current_user.id).first()
        book_in_lib = Library.query.filter_by(book_id=book.id, user_id=current_user.id).first()
        book_in_wishlist = WishList.query.filter_by(book_id=book.id, user_id=current_user.id).first()
    else:
        book_in_cart = None
        book_in_lib = None
        book_in_wishlist = None

    return render_template('main/comic_info.html', title='Comics info', book=book,
                           in_wishlist=book_in_wishlist is not None,
                           in_lib=book_in_lib is not None, in_cart=book_in_cart is not None)


@main.route('/top-picks')
def top_picks():
    page = request.args.get('page', 1, type=int)
    top_picks_list = ComicBook.query.filter_by(top_pick=True).paginate(page=page, per_page=8)

    left_over = len(top_picks_list.items)
    rows = 1
    if left_over > 4:
        rows = 2

    return render_template('main/recommended.html', title='Top Picks', comics=top_picks_list, len=len,
                           rows=rows, left_over=left_over)
    
    
@main.route("/search")
def search():
    search_query = request.args.get("q")
    all_comics = ComicBook.query.all()
    title_list = [comic for comic in all_comics if search_query.lower() in comic.title.lower()]
    category_list = [comic for comic in all_comics if search_query.lower() in comic.category.lower()]
    author_list = [comic for comic in all_comics if search_query.lower() in comic.author.lower()]
    length = 1
    
    if len(title_list) == len(category_list) == len(author_list) == 0:
        length = 0
            
    return render_template("main/search.html", title=f"Search for\"{search_query}\"", search_query=search_query, all_comics=all_comics, length=length)
    

@main.route('/watch')
def series():
    return render_template('main/series.html', title='Watch Series')

mysite/website/supplier/routes.py
from datetime import datetime

from flask import Blueprint, flash, redirect, url_for, render_template, request, abort
from flask_login import login_required, current_user

from website import bcrypt,db
from website.models import ComicBook, Library, Cart, WishList, Freelancer, Order, User
from website.supplier.forms import AddComic, AddFreelancer

supplier = Blueprint('supplier', __name__)


# supplier pass: il0v#Ch33s301

@supplier.route('/supplier')
@login_required
def supplier_home():
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    return render_template('supplier/home.html', title='Admin')

# Add a book
@supplier.route('/supplier/add-comic', methods=['GET', 'POST'])
@login_required
def add_comic():
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    form = AddComic()

    if form.validate_on_submit():
        category = form.category.data
        title = form.title.data
        author = form.author.data.title()
        illustrator = form.illustrator.data.title()
        price = int(form.price.data)
        release_date = form.date.data.strftime('%d/%m/%Y')
        description = form.description.data
        top_pick = form.top_pick.data
        filename = form.cover_image.data.filename
        title_query = form.cover_image.data.filename[:-4].lower()
        category_query = category.replace(':', '').replace('\'', '').replace(' ', '-').lower()
        stock_quantity = form.stock_quantity.data
        
        book = ComicBook(category=category, title=title, author=author, illustrator=illustrator, price=price,
                         release_date=release_date, description=description, top_pick=top_pick, filename=filename,
                         title_query=title_query, category_query=category_query, stock_quantity=stock_quantity)
        db.session.add(book)
        db.session.commit()

        flash('Book added to shelves. ', 'success')
        return redirect(url_for('supplier.add_comic'))

    return render_template('supplier/add_book.html', title='Add a book', form=form)

@supplier.route('/supplier/update-book')
@login_required
def all_comics():
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    page = request.args.get('page', 1, type=int)
    comics = ComicBook.query.paginate(page=page, per_page=4)
    return render_template('supplier/all_comics.html', title='Update', comics=comics)


@supplier.route('/supplier/update-book/<title_query>', methods=['GET', 'POST'])
@login_required
def update_comic(title_query):
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    form = AddComic()

    book = ComicBook.query.filter_by(title_query=title_query).first()

    if request.method == 'GET':
        form.category.data = book.category
        form.title.data = book.title
        form.author.data = book.author
        form.illustrator.data = book.illustrator
        form.price.data = book.price
        form.date.data = datetime.strptime(book.release_date, '%d/%m/%Y')
        form.description.data = book.description
        form.top_pick.data = book.top_pick
        form.stock_quantity.data = book.stock_quantity

    if form.validate_on_submit():
        book.filename = form.cover_image.data.filename
        book.category = form.category.data
        book.title = form.title.data
        book.author = form.author.data.title()
        book.illustrator = form.illustrator.data.title()
        book.price = int(form.price.data)
        book.release_date = form.date.data.strftime('%d/%m/%Y')
        book.description = form.description.data
        book.title_query = form.cover_image.data.filename[:-4].lower()
        book.category_query = form.category.data.replace(':', '').replace('\'', '').replace(' ', '-').lower()
        book.stock_quantity = form.stock_quantity.data
        db.session.commit()
        flash(f'Comic has been updated', 'success')
        return redirect(url_for('supplier.all_comics'))

    return render_template('supplier/add_book.html', title='Add a book', form=form)

@supplier.route('/supplier/delete-book/<title_query>', methods=['GET', 'POST'])
@login_required
def delete_book(title_query):
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    page = request.args.get('page', 1, type=int)
    comic = ComicBook.query.filter_by(title_query=title_query).first()
    lib = Library.query.filter_by(comic_book=comic).all()
    cart = Cart.query.filter_by(comic_book=comic).all()
    wish = WishList.query.filter_by(comic_book=comic).all()

    # Remove from every library, cart and wishlist if a book is deleted from the database
    for i in lib:
        db.session.delete(i)
    for j in cart:
        db.session.delete(j)
    for k in wish:
        db.session.delete(k)
    db.session.delete(comic)
    db.session.commit()
    return redirect(url_for('supplier.all_comics', page=page))

# ============================== Freelancers =====================================
@supplier.route('/supplier/add-freelancer', methods=['GET', 'POST'])
@login_required
def add_freelancer():
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    form = AddFreelancer()

    if form.validate_on_submit():
        freelancer = Freelancer(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            phone=form.phone.data,
            password = bcrypt.generate_password_hash(form.password.data).decode('utf-8'),
            address=form.address.data,
            country=form.country.data
        )
        
        db.session.add(freelancer)
        db.session.commit()

        flash('Freelancer added.', 'success')
        return redirect(url_for('supplier.add_freelancer'))

    return render_template('supplier/add_freelancer.html', title='Add a freelancer', form=form)


@supplier.route('/supplier/all-freelancers')
@login_required
def all_freelancers():
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    page = request.args.get('page', 1, type=int)
    query = request.args.get('query', '', type=str)
    sort_by = request.args.get('sort_by', 'first_name', type=str)
    order = request.args.get('order', 'asc', type=str)

    freelancers = Freelancer.query

    if query:
        freelancers = freelancers.filter(
            Freelancer.first_name.ilike(f'%{query}%') | 
            Freelancer.last_name.ilike(f'%{query}%') |
            Freelancer.email.ilike(f'%{query}%')
        )

    if sort_by and order:
        order_func = getattr(getattr(Freelancer, sort_by), order)
        freelancers = freelancers.order_by(order_func())

    freelancers = freelancers.paginate(page=page, per_page=4)

    return render_template('supplier/all_freelancers.html', title='All Freelancers', freelancers=freelancers)


@supplier.route('/supplier/update-freelancer/<int:id>', methods=['GET', 'POST'])
@login_required
def update_freelancer(id):
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    freelancer = Freelancer.query.get_or_404(id)
    form = AddFreelancer()

    if request.method == 'GET':
        form.first_name.data = freelancer.first_name
        form.last_name.data = freelancer.last_name
        form.email.data = freelancer.email
        form.phone.data = freelancer.phone
        form.address.data = freelancer.address
        form.country.data = freelancer.country

    if form.validate_on_submit():
        freelancer.first_name = form.first_name.data
        freelancer.last_name = form.last_name.data
        freelancer.email = form.email.data
        freelancer.phone = form.phone.data
        freelancer.address = form.address.data
        freelancer.country = form.country.data

        db.session.commit()
        flash('Freelancer has been updated.', 'success')
        return redirect(url_for('supplier.all_freelancers'))

    return render_template('supplier/add_freelancer.html', title='Update a freelancer', form=form)


@supplier.route('/supplier/delete-freelancer/<int:freelancer_id>', methods=['POST'])
@login_required
def delete_freelancer(freelancer_id):
    if current_user.email != 'supplier@supplier.com':
        abort(403)

    page = request.args.get('page', 1, type=int)
    freelancer = Freelancer.query.get_or_404(freelancer_id)

    db.session.delete(freelancer)
    db.session.commit()

    flash('Freelancer has been deleted successfully.', 'success')
    return redirect(url_for('supplier.all_freelancers', page=page))

# ============================== Orders =====================================
@supplier.route('/supplier/all-orders')
@login_required
def all_orders():
    if current_user.email != 'supplier@supplier.com':
        abort(403)
    
    sort_by = request.args.get('sort_by', 'date_ordered')
    order = request.args.get('order', 'asc')
    query = request.args.get('query', '')

    orders_query = Order.query.filter(
        (Order.id == query) |
        (Order.customer.has(User.first_name.ilike(f'%{query}%'))) |
        (Order.customer.has(User.last_name.ilike(f'%{query}%'))) |
        (Order.customer.has(User.email.ilike(f'%{query}%')))
    )

    # Apply sorting
    if order == 'asc':
        orders_query = orders_query.order_by(getattr(Order, sort_by).asc())
    else:
        orders_query = orders_query.order_by(getattr(Order, sort_by).desc())

    # Paginate the results
    page = request.args.get('page', 1, type=int)
    orders_page = orders_query.paginate(page=page, per_page=4)

    return render_template('supplier/all_orders.html', title='All Orders', orders=orders_page)

# @supplier.route('/supplier/all-orders')
# @login_required
# def all_orders():
#     orders = Order.query.all()
#     return render_template('supplier/all_orders.html', orders=orders)

@supplier.route('/supplier/view-order/<int:order_id>', methods=['GET'])
@login_required
def view_order(order_id):
    if current_user.email != 'supplier@supplier.com':
        abort(403)
        

mysite/website/templates/supplier/all_comics.html
{% extends "supplier/base.html" %}
{% block styles %}
<!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"> -->
{% endblock styles %}

{% block content %}
<div class="container-md mt-md-3 text-center ms-auto me-auto d-flex" style="max-width: 1048px;">
    {% for comic in comics.items %}
        <div class="card me-2 ms-2 comic-card p-2 bg-light" style="width: 18rem; border: none; min-width: 222px;">
            <img src="{{ url_for('static', filename='images/comic_images/'+comic.filename) }}" class="card-img-top" alt="Comic Book Cover">
            <div class="card-body">
                <h5 class="card-title">{{ comic.title }}</h5>
                <span class="fs-6">{{ comic.release_date }}</span>
                <br>
                <span class="fs-6">Stock: {{ comic.stock_quantity }}</span>
                <br><br>
                <div class="d-flex mt-auto">
                    <a href="{{ url_for('supplier.update_comic', title_query=comic.title_query) }}" class="btn btn-primary">Update</a>
                    <!-- Modal button -->
                    <button type="button" class="btn btn-outline-danger ms-auto" data-bs-toggle="modal" data-bs-target="#deleteModal{{ comic.title_query }}">
                        Delete
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal{{ comic.title_query }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ comic.title_query }}" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel{{ comic.title_query }}">Confirm deletion</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete this book?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <form action="{{ url_for('supplier.delete_book', title_query=comic.title_query) }}" method="post">
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<div class="container ms-auto me-auto">
    {% for page_num in comics.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if comics.page == page_num %}
                <a href="{{ url_for('supplier.all_comics', page=page_num) }}" class="btn btn-primary mb-4">{{ page_num }}</a>
            {% else %}
                <a href="{{ url_for('supplier.all_comics', page=page_num) }}" class="btn btn-outline-primary mb-4">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

mysite/website/templates/supplier/all_freelancers.html
{% extends "supplier/base.html" %}

{% block content %}
<div class="container-md mt-md-3 text-center ms-auto me-auto" style="max-width: 1048px;">

    <form method="GET" action="{{ url_for('supplier.all_freelancers') }}" class="d-flex justify-content-center mb-4">
        <input type="text" name="query" class="form-control me-2" placeholder="Search by name or email" value="{{ request.args.get('query', '') }}" style="max-width: 300px;">
        <button type="submit" class="btn btn-outline-primary">Search</button>
    </form>

    <div class="btn-group mb-4">
        <a href="{{ url_for('supplier.all_freelancers', sort_by='first_name', order='asc', query=request.args.get('query', '')) }}" class="btn btn-outline-primary">Sort by Name Ascending</a>
        <a href="{{ url_for('supplier.all_freelancers', sort_by='first_name', order='desc', query=request.args.get('query', '')) }}" class="btn btn-outline-primary">Sort by Name Descending</a>
    </div>

    <div class="d-flex flex-wrap justify-content-center">
        {% for freelancer in freelancers.items %}
            <div class="card me-2 ms-2 p-2 bg-light" style="width: 18rem; border: none; min-width: 222px;">
                <div class="card-body">
                    <h4>{{ freelancer.first_name }} {{ freelancer.last_name }}</h4>
                    <p class="card-text">{{ freelancer.email }}</p>
                    <span class="fs-6">{{ freelancer.phone }}</span>
                    <br><br>
                    <div class="d-flex mt-auto">
                        <a href="{{ url_for('supplier.update_freelancer', id=freelancer.id) }}" class="btn btn-primary">Update</a>
                        <button type="button" class="btn btn-outline-danger ms-auto" data-bs-toggle="modal" data-bs-target="#deleteModal{{ freelancer.id }}">
                            Delete
                        </button>
                        
                        <div class="modal fade" id="deleteModal{{ freelancer.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Confirm deletion</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure you want to delete this freelancer?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                        <form action="{{ url_for('supplier.delete_freelancer', freelancer_id=freelancer.id) }}" method="post">
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<div class="container ms-auto me-auto">
    {% for page_num in freelancers.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if freelancers.page == page_num %}
                <a href="{{ url_for('supplier.all_freelancers', page=page_num, query=request.args.get('query', ''), sort_by=request.args.get('sort_by', 'first_name'), order=request.args.get('order', 'asc')) }}" class="btn btn-primary mb-4">{{ page_num }}</a>
            {% else %}
                <a href="{{ url_for('supplier.all_freelancers', page=page_num, query=request.args.get('query', ''), sort_by=request.args.get('sort_by', 'first_name'), order=request.args.get('order', 'asc')) }}" class="btn btn-outline-primary mb-4">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

mysite/website/templates/supplier/all_orders.html
{% extends "supplier/base.html" %}
{% block content %}
<div class="container mt-5">
    <h2 class="mb-4 text-center">All Orders</h2>

    <form method="GET" class="mb-4 d-flex justify-content-center">
        <input type="text" name="query" class="form-control w-25" placeholder="Search by name, email, or order ID" value="{{ request.args.get('query', '') }}">
        <button type="submit" class="btn btn-primary ml-2">Search</button>
    </form>

    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th><a href="{{ url_for('supplier.all_orders', sort_by='id', order='asc' if sort_by != 'id' or order == 'desc' else 'desc') }}">Order ID</a></th>
                    <th><a href="{{ url_for('supplier.all_orders', sort_by='customer.first_name', order='asc' if sort_by != 'customer.first_name' or order == 'desc' else 'desc') }}">Customer Name</a></th>
                    <th><a href="{{ url_for('supplier.all_orders', sort_by='customer.email', order='asc' if sort_by != 'customer.email' or order == 'desc' else 'desc') }}">Customer Email</a></th>
                    <th><a href="{{ url_for('supplier.all_orders', sort_by='date_ordered', order='asc' if sort_by != 'date_ordered' or order == 'desc' else 'desc') }}">Date Ordered</a></th>
                    <th>Status</th>
                    <th>Total</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders.items %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.customer.first_name }} {{ order.customer.last_name }}</td>
                    <td>{{ order.customer.email }}</td>
                    <td>{{ order.date_ordered.strftime('%d/%m/%Y') }}</td>
                    <td>{{ order.status }}</td>
                    <td>${{ order.total }}</td>
                    <td>
                        <a href="{{ url_for('supplier.view_order', order_id=order.id) }}" class="btn btn-info btn-sm">View</a>
                        <form action="{{ url_for('supplier.delete_order', order_id=order.id) }}" method="POST" style="display:inline;">
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="7" class="text-center">No orders found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if orders.has_prev %}
            <li class="page-item"><a class="page-link" href="{{ url_for('supplier.all_orders', page=orders.prev_num, sort_by=sort_by, order=order, query=request.args.get('query', '')) }}">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Previous</span></li>
            {% endif %}

            {% for page_num in orders.iter_pages() %}
                {% if page_num %}
                    <li class="page-item {% if page_num == orders.page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for('supplier.all_orders', page=page_num, sort_by=sort_by, order=order, query=request.args.get('query', '')) }}">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">…</span></li>
                {% endif %}
            {% endfor %}

            {% if orders.has_next %}
            <li class="page-item"><a class="page-link" href="{{ url_for('supplier.all_orders', page=orders.next_num, sort_by=sort_by, order=order, query=request.args.get('query', '')) }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">Next</span></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

mysite/website/templates/supplier/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% block styles %}{% endblock %}
    <style>
        i {
            font-size: 20px;
        }
    </style>
    <title>NebulaNarratives | {{ title }}</title>
</head>
<body>
    <!-- Header -->
    <header>
        <nav class="navbar navbar-expand-md navbar-light pt-md-2 pb-md-2 mb-4 bg-light" >
            <div class="container-md max-width" style="max-width: 82rem;">
                <span class="logo ">NebulaNarratives | </span>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse mb-lg-0" id="navbarNav">
                    <ul class="navbar-nav ms-auto me-auto">
                        <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('supplier.supplier_home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('supplier.add_comic') }}">Add a comic</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('supplier.all_comics') }}">Update a comic</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{{ url_for('supplier.add_freelancer') }}">Add an freelancer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('supplier.all_freelancers') }}">Update or delete an freelancer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('supplier.all_orders') }}">View all orders</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Exit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <!-- Main -->
    <main>
        <!-- Flash messages display here -->
        <div class="container-md" >
            <div class="">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} ms-auto me-auto col-md-8 mt-4 mb-4"> {{ message }}</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>

        <!-- Main content -->
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>