mysite/website/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField 
from wtforms.validators import Length


class Search(FlaskForm):
    query = StringField('Title')

mysite/website/main/routes.py
from flask import Blueprint, render_template, request
from flask_login import current_user

from website.models import ComicBook, Cart, Library, WishList

main = Blueprint('main', __name__)


# The home page route
@main.route('/')
def home():
    top_picks = ComicBook.query.filter_by(top_pick=True).all()[:6]
    kadoko_list = ComicBook.query.filter_by(category_query='kadoko').all()[:6]
    latest = ComicBook.query.all()[-1:-7:-1]
    free = ComicBook.query.filter_by(price=-1).all()
    return render_template('main/home.html', title='Home', top_picks=top_picks,
                           kadoko_list=kadoko_list, latest=latest, freebies=free)


@main.route('/about')
def about():
    return render_template('main/about.html', title='About us')


@main.route('/comics')
def comics():
    comic_list = {
        'action': ComicBook.query.filter_by(category_query='action').all()[0:6],
        'jabulani': ComicBook.query.filter_by(category_query='jabulani').all()[0:6],
        'horror': ComicBook.query.filter_by(category_query="horror").all()[0:6],
        'comedy': ComicBook.query.filter_by(category_query='comedy').all()[0:6],
        'fantasy': ComicBook.query.filter_by(category_query='fantasy').all()[0:6],
        'romance': ComicBook.query.filter_by(category_query='romance').all()[0:6],
    }

    return render_template('main/comics.html', title='Comics', comics=comic_list)


@main.route('/comic-category/<category_query>')
def comic_category(category_query):
    page = request.args.get('page', 1, type=int)
    category_list = ComicBook.query.filter_by(category_query=category_query).paginate(page=page, per_page=8)

    left_over = len(category_list.items)
    rows = 1
    if left_over > 4:
        rows = 2
    return render_template('/main/category_info.html', title=category_list.items[0].category,
                           comics=category_list, len=len, rows=rows, left_over=left_over)


@main.route('/comic-info/<title_query>', methods=['GET', 'POST'])
def comic_info(title_query):
    # Get the book
    book = ComicBook.query.filter_by(title_query=title_query).first()

    if book is None:
        return "Book not found", 404  # Handle the case where the book is not found

    if current_user.is_authenticated:
        # Use foreign keys directly
        book_in_cart = Cart.query.filter_by(book_id=book.id, user_id=current_user.id).first()
        book_in_lib = Library.query.filter_by(book_id=book.id, user_id=current_user.id).first()
        book_in_wishlist = WishList.query.filter_by(book_id=book.id, user_id=current_user.id).first()
    else:
        book_in_cart = None
        book_in_lib = None
        book_in_wishlist = None

    return render_template('main/comic_info.html', title='Comics info', book=book,
                           in_wishlist=book_in_wishlist is not None,
                           in_lib=book_in_lib is not None, in_cart=book_in_cart is not None)


@main.route('/top-picks')
def top_picks():
    page = request.args.get('page', 1, type=int)
    top_picks_list = ComicBook.query.filter_by(top_pick=True).paginate(page=page, per_page=8)

    left_over = len(top_picks_list.items)
    rows = 1
    if left_over > 4:
        rows = 2

    return render_template('main/recommended.html', title='Top Picks', comics=top_picks_list, len=len,
                           rows=rows, left_over=left_over)
    
    
@main.route("/search")
def search():
    search_query = request.args.get("q")
    all_comics = ComicBook.query.all()
    title_list = [comic for comic in all_comics if search_query.lower() in comic.title.lower()]
    category_list = [comic for comic in all_comics if search_query.lower() in comic.category.lower()]
    author_list = [comic for comic in all_comics if search_query.lower() in comic.author.lower()]
    length = 1
    
    if len(title_list) == len(category_list) == len(author_list) == 0:
        length = 0
            
    return render_template("main/search.html", title=f"Search for\"{search_query}\"", search_query=search_query, all_comics=all_comics, length=length)
    

@main.route('/watch')
def series():
    return render_template('main/series.html', title='Watch Series')

mysite/website/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request,Flask, render_template,send_file,Response
from flask_login import current_user, login_user, logout_user, login_required
import matplotlib.pyplot as plt
import base64
from io import BytesIO
from PIL import Image
from reportlab.pdfgen import canvas
from wtforms import StringField
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
from website import bcrypt, db
from website.models import User, Cart, Library, CardDetails, WishList, ComicBook
from wtforms.validators import DataRequired
from website.users.forms import SignUp, Login, UpdatePassword, UpdateEmail

# Blueprint
users = Blueprint('users', __name__)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = SignUp()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            flash('Email is already registered. Please log in or use a different email.', 'danger')
            return redirect(url_for('users.signup'))
        
        existing_phone = User.query.filter_by(phone=form.phone.data).first()
        if existing_phone:
            flash('Phone number is already registered. Please log in or use a different number.', 'danger')
            return redirect(url_for('users.signup'))
        
        first_name = form.first_name.data
        last_name = form.last_name.data
        email = form.email.data
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        phone = form.phone.data
        age = form.age.data
        country = form.country.data
        address = form.address.data
 
        name_query = (first_name + '-' + last_name).replace(' - ', '-').replace(':', '').replace('\'', '').replace(' ', '-').lower()
        user_num = len(User.query.all()) + 1

        user = User(first_name=first_name, last_name=last_name, email=email, password=password, phone=phone,age=age, country=country, address= address)
        
        db.session.add(user)
        db.session.commit()
        login_user(user, remember=form.remember.data)
        flash('Account created successfully', 'success')
        return redirect(url_for('main.home'))

    return render_template('user/signup.html', title='Sign up', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = Login()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Login successful', 'success')
            prev = request.args.get('next')
            if prev:
                return redirect(prev)
            return redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Incorrect email or password!', 'danger')
            return redirect(url_for('users.login'))
    return render_template('user/login.html', title='Login', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    cards = CardDetails.query.filter_by(owner=current_user).all()
    amount = len(Library.query.filter_by(bought_by=current_user).all())
    return render_template('user/account_settings.html', title='Account', cards=cards, number=len(cards), amount=amount)


@users.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('main.home'))
    else:
        return redirect(url_for('main.home'))


@users.route('/account/update-email', methods=['GET', 'POST'])
@login_required
def update_email():
    form = UpdateEmail()
    if request.method == 'GET':
        form.email.data = current_user.email
    elif form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        user.email = form.email.data
        db.session.commit()
        flash('Your email has been updated!', 'success')
        return redirect(url_for('users.account'))
    return render_template('user/update_email.html', title='Account', form=form)


@users.route('/account/update-password', methods=['GET', 'POST'])
@login_required
def update_password():
    form = UpdatePassword()

    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if bcrypt.check_password_hash(user.password, form.current_password.data):
            user.password = bcrypt.generate_password_hash(form.new_password.data)
            db.session.commit()
            flash('Your password has been updated!', 'success')
            return redirect(url_for('users.account'))
        else:
            flash('Your current password is incorrect.', 'danger')
    return render_template('user/update_password.html', title='Account', form=form)


@users.route('/cart')
@login_required
def cart():
    cart_list = Cart.query.filter_by(buyer=current_user).all()
    quantity = request.form.getlist("quantity")
    print(quantity)
    total = sum(comic.comic_book.price for comic in cart_list)
    return render_template('user/cart.html', title='Cart', items=cart_list, length=len(cart_list), total=total)


@users.route('/wishlist')
@login_required
def wishlist():
    wish_list = WishList.query.filter_by(buyer=current_user).all()
    in_cart = Cart.query.filter_by(buyer=current_user).first()
    return render_template('user/wishlist.html', title='Cart', items=wish_list, length=len(wish_list), in_cart=in_cart is not None)


@users.route('/library')
@login_required
def library():
    page = request.args.get('page', 1, type=int)
    library_items = Library.query.filter_by(bought_by=current_user).paginate(page=page, per_page=8)
    return render_template('user/library.html', title='Library', items=library_items, length=library_items.total, len=len)
   
@users.route("/report")
@login_required
def report():
    sort_order = request.args.get('sort_order', 'none')
    
    if sort_order == 'asc':
        top_picks_list = ComicBook.query.order_by(ComicBook.stock_quantity.asc()).limit(10).all()
        report_pdf_path = "mysite/website/static/report/asc_report.pdf"
    elif sort_order == 'desc':
        top_picks_list = ComicBook.query.order_by(ComicBook.stock_quantity.desc()).limit(10).all()
        report_pdf_path = "mysite/website/static/report/desc_report.pdf"
    else:
        top_picks_list = ComicBook.query.limit(10).all()
        report_pdf_path = "mysite/website/static/report/unsorted_report.pdf"
    
    library = Library.query.filter_by(bought_by=current_user).all()
  
    plt.figure(figsize=(11, 9))
    plt.bar([comic.title for comic in top_picks_list], [comic.stock_quantity for comic in top_picks_list])
    plt.xlabel('Comic Book')
    plt.ylabel('Stock Quantity')
    plt.title('Top 10 Comics by Stock Quantity')
    plt.xticks(rotation=45, ha="right")
    
    report_image_path = "mysite/website/static/images/stock_quantity.png"
    plt.savefig(report_image_path)
  
    c = canvas.Canvas(report_pdf_path, pagesize=(800, 600))
    c.drawImage(report_image_path, 100, 40, 600)
    c.save()
    
    comics = [(comic.title, comic.stock_quantity) for comic in top_picks_list]
    
    return render_template("user/report.html", title="Report", comics=comics, library=library)

@users.route('/report/download')
@login_required
def download_pdf():
    sort_order = request.args.get('sort_order', 'none')
    
    if sort_order == 'asc':
        file_path = "static/report/asc_report.pdf"
    elif sort_order == 'desc':
        file_path = "static/report/desc_report.pdf"
    else:
        file_path = "static/report/unsorted_report.pdf"
    
    return send_file(file_path, as_attachment=True, mimetype="application/pdf", download_name="report.pdf")


@users.route("/report-income")
@login_required
def report_income():
    period = request.args.get('period', 'annual')  # Default
    top_picks_list = ComicBook.query.all()
    
    # Calculate income based on the selected period
    income_values = []
    if period == 'quarterly':
        income_values = [comic.price * comic.stock_quantity / 4 for comic in top_picks_list]
    elif period == 'biannual':
        income_values = [comic.price * comic.stock_quantity / 2 for comic in top_picks_list]
    else:  
        income_values = [comic.price * comic.stock_quantity for comic in top_picks_list]
    
    
    comic_titles = [comic.title for comic in top_picks_list]

    plt.figure(figsize=(11, 9))
    plt.bar(comic_titles[:10], income_values[:10])
    plt.xlabel('Comic Book')
    plt.ylabel('Total Income (R)')
    plt.title(f'Total Income per Comic Book ({period.capitalize()})')
    
    plt.xticks(rotation=45, ha="right")
    plot_path = f"mysite/website/static/images/stock_income_{period}.png"
    pdf_path = f"mysite/website/static/report_income/report_{period}.pdf"
    
    plt.savefig(plot_path)
    
    try:
        c = canvas.Canvas(pdf_path, pagesize=(800, 600))
        c.drawImage(plot_path, 100, 40, 600)
        c.save()
    except Exception as e:
        return f"Error generating report: {str(e)}", 500
    
    # Prepare comics data for the template
    comics = [(comic.title, income) for comic, income in zip(top_picks_list, income_values)]
    comics = comics[:10]
    
    return render_template(
        "user/report_income.html",title="Report",comics=comics,period=period)

@users.route('/report-income/report_income.pdf')
@login_required
def download_income_pdf():
    period = request.args.get('period', 'annual')  # Default 
    return send_file(
        f"static/report_income/report_{period}.pdf",
        as_attachment=True,
        mimetype="pdf",
        download_name=f"report_income_{period}.pdf"
    )

mysite/website/templates/main/category_info.html
{% extends "base.html" %}
{% block styles %}
<style>
    section {
        background-image: linear-gradient(to bottom left, rgb(248, 79, 107), rgb(223, 159, 40));
    }

    h2 {
        color: white !important;
    }

    /* Comic book decorations */
    .card {
        margin: 1rem 0;
        padding: 0.4rem;
        background-color: darkblue;
        color: white;
        font-family: calibri;
        width: 225px; 
        min-width: 225px;
        height: 400.33px;
        border: none; 
    }

    .card a {
        color: white;
        text-decoration: none;
    }

    .display-grid {
        display: grid;
        justify-items: center;
        grid-template-columns: repeat(4, 1fr);
        grid-template-rows: repeat({{ rows }}, 1fr);
    }

    @media screen and (max-width: 1010px) {
        .display-grid {
            grid-template-columns: repeat(3, 1fr);
            grid-template-rows: repeat(3, 1fr);
        }
    }

    @media screen and (max-width: 792px) {
        .display-grid {
            grid-template-columns: repeat(2, 1fr);
            grid-template-rows: repeat(4, 1fr);
        }
    }

    @media screen and (max-width: 540px) {
        .display-grid {
            grid-template-columns: repeat(1, 1fr);
            grid-template-rows: repeat({{ left_over }}, 1fr);
        }
    }
</style>
{% endblock styles %}

{% block content %}
<section>
    <div class="max-width p-4 ms-auto me-auto">
        <h2 class="h2">{{ title }}</h2>
        <div class="display-grid">
            {% for comic in comics.items %}
            <div class="card">
                <a href="{{ url_for('main.comic_info', title_query=comic.title) }}">
                    <img src="{{ url_for('static', filename='images/comic_images/'+comic.filename) }}" class="card-img-top" alt="Comic Book Cover">
                </a>
                <div class="card-body text-center">
                    <h5 class="card-title h5 mt-0 mb-1">{{ comic.title }}</h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <nav aria-label="Page navigation example" style="display: flex; justify-content: center;">
        <ul class="pagination">
            <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
            </li>
            {% for page_num in comics.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
                {% if page_num %}
                    {% if comics.page == page_num %}
                        <li class="page-item active"><a href="{{ url_for('main.comic_category', category_query=title.replace(':', '').replace('\'', '').replace(' ', '-').lower(), page=page_num) }}" class="page-link">{{ page_num }}</a></li>
                    {% else %}
                        <li class="page-item"><a href="{{ url_for('main.comic_category', category_query=title.replace(':', '').replace('\'', '').replace(' ', '-').lower(), page=page_num) }}" class="page-link">{{ page_num }}</a></li>
                    {% endif %}
                {% else %}
                <li class="page-item">...</li>
                {% endif %}
            {% endfor %}
            <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
            </li>
            
        </ul>
    </nav>
</section>

{% endblock %}

mysite/website/templates/main/comic_info.html
{% extends "base.html" %}
{% block styles %}
<style>
    .icon-link {
        font-size: 1.5rem;
        color: var(--primary-text-colour);
        text-decoration: none;
        display: flex;
        align-items: center;
    }

    a {
        text-decoration: none;
    }

    .icon-link:hover {
        cursor: pointer;
    }

    .btn-{
        background-color: #3b3b3b;
        color: white;
        border-radius: 0 !important;
    }

    section img {
        width: 92%;
        height: auto;
        margin: auto;
        box-shadow: 5px 8px 5px 5px rgba(17, 17, 17, 0.492);
    }

    @media screen and (max-width: 768px) {
        section img {
            width: 65%;
            margin: auto;
            text-align: center;
        }
    }
</style>

{% endblock styles %}

{% block content %}
<section>
    <div class="max-width p-4 pt-3 pb-3 mt-4 d-flex" style="background-color: var(--dark)">
        <a href="{{ url_for('main.comics') }}" class="icon-link icon-link-hover ms-3 me-auto">
            <i class="bi bi-arrow-left-circle-fill"></i>  Back
        </a>
        <a href="{{ url_for('users.cart') }}" class="btn btn-warning ms-auto mt-auto mb-auto" style="border-radius: 0px;">Go to cart</a>
    </div>
    <div class="container max-width pb-5 pt-5 ms-auto me-auto row row-cols-1 row-cols-md-3" style="background-color: rgba(194, 194, 194, 0.4);">
        <div class="col-md-4 book-cover ms-auto me-auto">
            <img src="{{ url_for('static', filename='images/comic_images/' + book.filename) }}" alt="Comic cover">
        </div>
        <div class="col-md-8 mt-md-0 mt-4">
            <div class="">
                <h2 class="h2 mb-2">{{ book.title }}</h2>
                <p class="display-6 fs-5">Date released: {{ book.release_date }}</p>
                <p class="display-4 pt-2 pb-2">R{{ book.price }}0</p>
                <p class="display-6 fs-5">Authors: {{ book.author }}</p>
                <p class="display-6 fs-5">Illustrators: {{ book.illustrator }}</p>
                <p class="display-6 fs-5"><strong>Available Quantity: {{ book.stock_quantity }}</strong></p> <!-- Added stock quantity here -->
                <div class="d-flex">
                    {% if not in_lib %}
                        <!-- Cart add/remove form -->
                        {% if not in_cart %}
                            <form action="{{ url_for('action.add_to_cart', title_query=book.title_query) }}" method="post">
                                <fieldset>
                                    <button type="submit" class="btn btn-primary mb-2 mt-2 me-auto btn-lightdark">
                                        Add to cart
                                    </button>
                                </fieldset>
                            </form>
                        {% else %}
                            <form action="{{ url_for('action.remove_from_cart', title_query=book.title_query, next=request.url) }}" method="post">
                                <fieldset>
                                    <button type="submit" class="btn btn-primary mb-2 mt-2 me-auto btn-lightdark" >
                                        Remove from cart
                                    </button>
                                </fieldset>
                            </form>
                        {% endif %}

                        <!-- Wishlist add/remove form -->
                        {% if not in_wishlist %}
                            <form action="{{ url_for('action.add_to_wishlist', title_query=book.title_query) }}" method="post">
                                <fieldset>
                                    <button type="submit" class="btn btn-primary mb-2 mt-2 me-auto ms-3" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Add to Wishlist">
                                        <i class="bi bi-heart"></i>
                                    </button>
                                </fieldset>
                            </form>
                        {% else %}
                            <form action="{{ url_for('action.remove_from_wishlist', title_query=book.title_query) }}" method="post">
                                <fieldset>
                                    <button type="submit" class="btn btn-primary mb-2 mt-2 me-auto ms-3" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Remove from Wishlist">
                                        <i class="bi bi-heart-fill" style="color: red"></i>
                                    </button>
                                </fieldset>
                            </form>
                        {% endif %}
                    {% else %}
                        <!-- View library -->
                        <button type="submit" class="btn btn-primary mb-2 mt-2 me-auto" >
                            <a href="{{ url_for('users.library') }}">In library</a>
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="p-4" style="background-color: rgba(95, 9, 9, 0.2)">
        <div class="max-width">
            <h3 class="h3 mb-4">Description:</h3>
            <span class="display-5 fs-5 fw-light">{{ book.description }}</span>
        </div>
    </div>
</section>
{% endblock %}

mysite/website/templates/main/comics.html
{% extends "base.html" %}
{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/comics.css') }}">
{% endblock styles %}

{% block content %}
{% for key in comics %}
	<section class="pt-3 pb-3">
		<div class="max-width ms-auto me-auto">
			<div class="category-header d-flex">
				<h3 class="h3 category-title"><a href="{{ url_for('main.comic_category', category_query=key) }}">{{ key.capitalize()}}</a></h3>
				<div class="scroll-buttons ms-auto me-md-5 me-3">
					<!-- <span class="fs-5"><a href="#">More ></a></span> -->
					<!-- <i class="bi bi-caret-left-fill"></i>
					<i class="bi bi-caret-right-fill"></i> -->
				</div>
			</div>
			<div class="comic-shelf">
				{% for comic in comics[key] %}
					<div class="card">
						<a href="{{ url_for('main.comic_info', title_query=comic.title_query) }}">
							<img src="{{ url_for('static', filename='images/comic_images/'+comic.filename) }}" class="card-img-top" alt="Comic Book Cover">
						</a>
						<div class="card-body">
							<h5 class="card-title h6 mt-0 mb-1">{{ comic.title }}</h5>
							<small class="">By {{ comic.author }}</small>
						</div>
					</div>
				{% endfor %}
				<div class="card me-2 ms-2 mt-auto mb-auto comic-card p-2">
					<div class="card-body text-center">
						<a href="{{ url_for('main.comic_category', category_query=key) }}">
							<i class="bi bi-plus-circle" style="font-size: 2rem"></i><br>
							<p>More</p>
						</a>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endfor %}

<script>
	// var button = document.querySelector('.bi-arrow-right');
	// button.onclick = function () {
	// 	var container = document.querySelector('.comic-shelf');
	// 	sideScroll(container,'right',25,100,10);
	// };

	// var back = document.getElementById('.bi-arrow-left');
	// back.onclick = function () {
	// 	var container = document.querySelector('.comic-shelf');
	// 	sideScroll(container,'left',25,100,10);
	// };

	// function scroll(element, ) {

	// }

	// function sideScroll(element,direction,speed,distance,step){
	// 	scrollAmount = 0;
	// 	var slideTimer = setInterval(function(){
	// 		if(direction == 'left'){
	// 			element.scrollLeft -= step;
	// 		} else {
	// 			element.scrollLeft += step;
	// 		}
	// 		scrollAmount += step;
	// 		if(scrollAmount >= distance){
	// 			window.clearInterval(slideTimer);
	// 		}
	// 	}, speed);
	// }
</script>

{% endblock %}

mysite/website/templates/main/home.html
{% extends "base.html" %}
{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock styles %}

{% block content %}
<section>
    <!-- <div class="container-fluid hero mb-4 ps-0 pe-0" style="border-top: 5px solid #333; border-bottom: 5px solid #333;" > -->
    <div class="container-fluid hero ps-0 pe-0 text-center text-md-start" data-bs-ride="carousel">
        <div id="carouselExampleIndicators" class="carousel slide">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="max-width">
                        <div class="carousel-caption mb-4 text-start carousel-slide-1">
                            <h1 class="h2 mb-4">New Year, New Comic!</h1>
                            <p>Read the latest comic which is set in the Kadoko Universe. Kadoko is faced with another tough villian, Odashi. Find out now who this villian is.</p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="max-width">
                        <div class="carousel-caption mb-4">
                            <h5 class="h2">MEio Adventures</h5>
                            <p>MEio—the girl with eyes like fractured mirrors—unravels forgotten secrets. Her footsteps echo through haunted streets, and the darkness clings to her like a curse. </p>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="max-width">
                        <div class="carousel-caption mb-4 text-end">
                            <h5 class="h2">Rekon: The Ronin</h5>
                            <p>Watch how good of a warrior of the person who trained Genesi was.</p>
                        </div>
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
</section>

<section class="pt-5">
    <div class="container-md max-width">
        <code>PLEASE NOTE: This is a **FICTIONAL STORE**</code>
        <h4 class="h4 mb-4">Latest Comics</h4>
        <div class="comic-shelf">
			{% for comic in latest %}
				<div class="card">
					<a href="{{ url_for('main.comic_info', title_query=comic.title_query) }}">
						<img src="{{ url_for('static', filename='images/comic_images/'+comic.filename) }}" class="card-img-top" alt="Comic Book Cover">
					</a>
					<div class="card-body text-center">
						<h5 class="card-title h6 mt-1 mb-1">{{ comic.title }}</h5>
					</div>
				</div>
			{% endfor %}
			<div class="card me-2 ms-2 mt-auto mb-auto comic-card p-2">
				<div class="card-body text-center">
					<a href="{{ url_for('main.top_picks') }}">
						<i class="bi bi-plus-circle" style="font-size: 2rem"></i><br>
						<p>More</p>
					</a>
				</div>
			</div>
		</div>
    </div>
</section>

<section class="section-3">
    <div class="container-md max-width">
        <h4 class="h4 mb-4">Recommended For You</h4>
        <div class="comic-shelf">
			{% for comic in top_picks %}
				<div class="card">
					<a href="{{ url_for('main.comic_info', title_query=comic.title_query) }}">
						<img src="{{ url_for('static', filename='images/comic_images/'+comic.filename) }}" class="card-img-top" alt="Comic Book Cover">
					</a>
					<div class="card-body text-center">
						<h5 class="card-title h6 mt-1 mb-1">{{ comic.title }}</h5>
					</div>
				</div>
			{% endfor %}
			<div class="card me-2 ms-2 mt-auto mb-auto comic-card p-2">
				<div class="card-body text-center">
					<a href="{{ url_for('main.top_picks') }}">
						<i class="bi bi-plus-circle" style="font-size: 2rem"></i>
                        <br>
						<p>More</p>
					</a>
				</div>
			</div>
		</div>
    </div>
</section>

{% endblock %}

mysite/website/templates/main/series.html
{% extends "base.html" %}

{% block styles %}
<style>
    /* .series-grid {
        display: grid;
        grid-
    } */
</style>
{% endblock %}


{% block content %}
<div class="container-md mt-md-3 max-width">
    <h3 class="h3 display-3 mt-3 mb-3">Fre</h3>
    <div class="row row-cols-1 row-cols-md-3">
        <div class="col">
            <!-- <div class="card">
                <img src="{{ url_for('static', filename='images/series_covers/kadoko.jpg') }}" alt="">
            </div> -->
        </div>
        <div class="col"></div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}