mysite/website/main/routes.py
from flask import Blueprint, render_template, request
from flask_login import current_user

from website.models import ComicBook, Cart, Library, WishList

main = Blueprint('main', __name__)


# The home page route
@main.route('/')
def home():
    top_picks = ComicBook.query.filter_by(top_pick=True).all()[:6]
    kadoko_list = ComicBook.query.filter_by(category_query='kadoko').all()[:6]
    latest = ComicBook.query.all()[-1:-7:-1]
    free = ComicBook.query.filter_by(price=-1).all()
    return render_template('main/home.html', title='Home', top_picks=top_picks,
                           kadoko_list=kadoko_list, latest=latest, freebies=free)


@main.route('/about')
def about():
    return render_template('main/about.html', title='About us')


@main.route('/comics')
def comics():
    comic_list = {
        'action': ComicBook.query.filter_by(category_query='action').all()[0:6],
        'jabulani': ComicBook.query.filter_by(category_query='jabulani').all()[0:6],
        'horror': ComicBook.query.filter_by(category_query="horror").all()[0:6],
        'comedy': ComicBook.query.filter_by(category_query='comedy').all()[0:6],
        'fantasy': ComicBook.query.filter_by(category_query='fantasy').all()[0:6],
        'romance': ComicBook.query.filter_by(category_query='romance').all()[0:6],
    }

    return render_template('main/comics.html', title='Comics', comics=comic_list)


@main.route('/comic-category/<category_query>')
def comic_category(category_query):
    page = request.args.get('page', 1, type=int)
    category_list = ComicBook.query.filter_by(category_query=category_query).paginate(page=page, per_page=8)

    left_over = len(category_list.items)
    rows = 1
    if left_over > 4:
        rows = 2
    return render_template('/main/category_info.html', title=category_list.items[0].category,
                           comics=category_list, len=len, rows=rows, left_over=left_over)


@main.route('/comic-info/<title_query>', methods=['GET', 'POST'])
def comic_info(title_query):
    # Get the book
    book = ComicBook.query.filter_by(title_query=title_query).first()

    if book is None:
        return "Book not found", 404  # Handle the case where the book is not found

    if current_user.is_authenticated:
        # Use foreign keys directly
        book_in_cart = Cart.query.filter_by(book_id=book.id, user_id=current_user.id).first()
        book_in_lib = Library.query.filter_by(book_id=book.id, user_id=current_user.id).first()
        book_in_wishlist = WishList.query.filter_by(book_id=book.id, user_id=current_user.id).first()
    else:
        book_in_cart = None
        book_in_lib = None
        book_in_wishlist = None

    return render_template('main/comic_info.html', title='Comics info', book=book,
                           in_wishlist=book_in_wishlist is not None,
                           in_lib=book_in_lib is not None, in_cart=book_in_cart is not None)


@main.route('/top-picks')
def top_picks():
    page = request.args.get('page', 1, type=int)
    top_picks_list = ComicBook.query.filter_by(top_pick=True).paginate(page=page, per_page=8)

    left_over = len(top_picks_list.items)
    rows = 1
    if left_over > 4:
        rows = 2

    return render_template('main/recommended.html', title='Top Picks', comics=top_picks_list, len=len,
                           rows=rows, left_over=left_over)
    
    
@main.route("/search")
def search():
    search_query = request.args.get("q")
    all_comics = ComicBook.query.all()
    title_list = [comic for comic in all_comics if search_query.lower() in comic.title.lower()]
    category_list = [comic for comic in all_comics if search_query.lower() in comic.category.lower()]
    author_list = [comic for comic in all_comics if search_query.lower() in comic.author.lower()]
    length = 1
    
    if len(title_list) == len(category_list) == len(author_list) == 0:
        length = 0
            
    return render_template("main/search.html", title=f"Search for\"{search_query}\"", search_query=search_query, all_comics=all_comics, length=length)
    

@main.route('/watch')
def series():
    return render_template('main/series.html', title='Watch Series')

mysite/website/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request,Flask, render_template,send_file,Response
from flask_login import current_user, login_user, logout_user, login_required
import matplotlib.pyplot as plt
import base64
from io import BytesIO
from PIL import Image
from reportlab.pdfgen import canvas
from wtforms import StringField
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
from website import bcrypt, db
from website.models import User, Cart, Library, CardDetails, WishList, ComicBook
from wtforms.validators import DataRequired
from website.users.forms import SignUp, Login, UpdatePassword, UpdateEmail

# Blueprint
users = Blueprint('users', __name__)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = SignUp()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            flash('Email is already registered. Please log in or use a different email.', 'danger')
            return redirect(url_for('users.signup'))
        
        existing_phone = User.query.filter_by(phone=form.phone.data).first()
        if existing_phone:
            flash('Phone number is already registered. Please log in or use a different number.', 'danger')
            return redirect(url_for('users.signup'))
        
        first_name = form.first_name.data
        last_name = form.last_name.data
        email = form.email.data
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        phone = form.phone.data
        age = form.age.data
        country = form.country.data
        address = form.address.data
 
        name_query = (first_name + '-' + last_name).replace(' - ', '-').replace(':', '').replace('\'', '').replace(' ', '-').lower()
        user_num = len(User.query.all()) + 1

        user = User(first_name=first_name, last_name=last_name, email=email, password=password, phone=phone,age=age, country=country, address= address)
        
        db.session.add(user)
        db.session.commit()
        login_user(user, remember=form.remember.data)
        flash('Account created successfully', 'success')
        return redirect(url_for('main.home'))

    return render_template('user/signup.html', title='Sign up', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = Login()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Login successful', 'success')
            prev = request.args.get('next')
            if prev:
                return redirect(prev)
            return redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Incorrect email or password!', 'danger')
            return redirect(url_for('users.login'))
    return render_template('user/login.html', title='Login', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    cards = CardDetails.query.filter_by(owner=current_user).all()
    amount = len(Library.query.filter_by(bought_by=current_user).all())
    return render_template('user/account_settings.html', title='Account', cards=cards, number=len(cards), amount=amount)


@users.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('main.home'))
    else:
        return redirect(url_for('main.home'))


@users.route('/account/update-email', methods=['GET', 'POST'])
@login_required
def update_email():
    form = UpdateEmail()
    if request.method == 'GET':
        form.email.data = current_user.email
    elif form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        user.email = form.email.data
        db.session.commit()
        flash('Your email has been updated!', 'success')
        return redirect(url_for('users.account'))
    return render_template('user/update_email.html', title='Account', form=form)


@users.route('/account/update-password', methods=['GET', 'POST'])
@login_required
def update_password():
    form = UpdatePassword()

    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if bcrypt.check_password_hash(user.password, form.current_password.data):
            user.password = bcrypt.generate_password_hash(form.new_password.data)
            db.session.commit()
            flash('Your password has been updated!', 'success')
            return redirect(url_for('users.account'))
        else:
            flash('Your current password is incorrect.', 'danger')
    return render_template('user/update_password.html', title='Account', form=form)


@users.route('/cart')
@login_required
def cart():
    cart_list = Cart.query.filter_by(buyer=current_user).all()
    quantity = request.form.getlist("quantity")
    print(quantity)
    total = sum(comic.comic_book.price for comic in cart_list)
    return render_template('user/cart.html', title='Cart', items=cart_list, length=len(cart_list), total=total)


@users.route('/wishlist')
@login_required
def wishlist():
    wish_list = WishList.query.filter_by(buyer=current_user).all()
    in_cart = Cart.query.filter_by(buyer=current_user).first()
    return render_template('user/wishlist.html', title='Cart', items=wish_list, length=len(wish_list), in_cart=in_cart is not None)


@users.route('/library')
@login_required
def library():
    page = request.args.get('page', 1, type=int)
    library_items = Library.query.filter_by(bought_by=current_user).paginate(page=page, per_page=8)
    return render_template('user/library.html', title='Library', items=library_items, length=library_items.total, len=len)
   
@users.route("/report")
@login_required
def report():
    sort_order = request.args.get('sort_order', 'none')
    
    if sort_order == 'asc':
        top_picks_list = ComicBook.query.order_by(ComicBook.stock_quantity.asc()).limit(10).all()
        report_pdf_path = "mysite/website/static/report/asc_report.pdf"
    elif sort_order == 'desc':
        top_picks_list = ComicBook.query.order_by(ComicBook.stock_quantity.desc()).limit(10).all()
        report_pdf_path = "mysite/website/static/report/desc_report.pdf"
    else:
        top_picks_list = ComicBook.query.limit(10).all()
        report_pdf_path = "mysite/website/static/report/unsorted_report.pdf"
    
    library = Library.query.filter_by(bought_by=current_user).all()
  
    plt.figure(figsize=(11, 9))
    plt.bar([comic.title for comic in top_picks_list], [comic.stock_quantity for comic in top_picks_list])
    plt.xlabel('Comic Book')
    plt.ylabel('Stock Quantity')
    plt.title('Top 10 Comics by Stock Quantity')
    plt.xticks(rotation=45, ha="right")
    
    report_image_path = "mysite/website/static/images/stock_quantity.png"
    plt.savefig(report_image_path)
  
    c = canvas.Canvas(report_pdf_path, pagesize=(800, 600))
    c.drawImage(report_image_path, 100, 40, 600)
    c.save()
    
    comics = [(comic.title, comic.stock_quantity) for comic in top_picks_list]
    
    return render_template("user/report.html", title="Report", comics=comics, library=library)

@users.route('/report/download')
@login_required
def download_pdf():
    sort_order = request.args.get('sort_order', 'none')
    
    if sort_order == 'asc':
        file_path = "static/report/asc_report.pdf"
    elif sort_order == 'desc':
        file_path = "static/report/desc_report.pdf"
    else:
        file_path = "static/report/unsorted_report.pdf"
    
    return send_file(file_path, as_attachment=True, mimetype="application/pdf", download_name="report.pdf")


@users.route("/report-income")
@login_required
def report_income():
    period = request.args.get('period', 'annual')  # Default
    top_picks_list = ComicBook.query.all()
    
    # Calculate income based on the selected period
    income_values = []
    if period == 'quarterly':
        income_values = [comic.price * comic.stock_quantity / 4 for comic in top_picks_list]
    elif period == 'biannual':
        income_values = [comic.price * comic.stock_quantity / 2 for comic in top_picks_list]
    else:  
        income_values = [comic.price * comic.stock_quantity for comic in top_picks_list]
    
    
    comic_titles = [comic.title for comic in top_picks_list]

    plt.figure(figsize=(11, 9))
    plt.bar(comic_titles[:10], income_values[:10])
    plt.xlabel('Comic Book')
    plt.ylabel('Total Income (R)')
    plt.title(f'Total Income per Comic Book ({period.capitalize()})')
    
    plt.xticks(rotation=45, ha="right")
    plot_path = f"mysite/website/static/images/stock_income_{period}.png"
    pdf_path = f"mysite/website/static/report_income/report_{period}.pdf"
    
    plt.savefig(plot_path)
    
    try:
        c = canvas.Canvas(pdf_path, pagesize=(800, 600))
        c.drawImage(plot_path, 100, 40, 600)
        c.save()
    except Exception as e:
        return f"Error generating report: {str(e)}", 500
    
    # Prepare comics data for the template
    comics = [(comic.title, income) for comic, income in zip(top_picks_list, income_values)]
    comics = comics[:10]
    
    return render_template(
        "user/report_income.html",title="Report",comics=comics,period=period)

@users.route('/report-income/report_income.pdf')
@login_required
def download_income_pdf():
    period = request.args.get('period', 'annual')  # Default 
    return send_file(
        f"static/report_income/report_{period}.pdf",
        as_attachment=True,
        mimetype="pdf",
        download_name=f"report_income_{period}.pdf"
    )

mysite/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block styles %}{% endblock %}
    <title>NebulaNarratives | {{ title }}</title>
</head>
<body class="fw-normal">
    <!-- Header -->
    <header id="top">
        <nav class="nav-container">
            <!-- Navbar for screens wider than medium -->
            <ul class="nav d-none d-md-flex">
                {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown logged-in-button">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-circle"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ url_for('users.account') }}"><i class="bi bi-gear"></i>   Account settings </a></li>
                            <li><a class="dropdown-item" href="{{ url_for('users.library') }}"><i class="bi bi-book-fill"></i>  Library</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('users.report') }}"><i class="bi bi-clipboard2-data"></i>  Report</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('users.report_income') }}"><i class="bi bi-clipboard2-data"></i>  Report Income</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a></li>
                        </ul>
                    </li>
                    <li class="nav-item logged-in-button">
                        <a class="nav-link" href="{{ url_for('users.wishlist') }}"><i class="bi bi-heart-fill"></i></a>
                    </li>
                    <li class="nav-item logged-in-button">
                        <a class="nav-link" aria-current="page" href="{{ url_for('users.cart') }}"><i class="bi bi-cart4"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item logged-out-button">
                        <a class="nav-link" aria-current="page" href="{{ url_for('users.login') }}">Login</a>
                    </li>
                    <li class="nav-item logged-out-button">
                        <a class="nav-link" href="{{ url_for('users.signup') }}">Sign up</a>
                    </li>
                {% endif %}
            </ul>
            <div class="p-3 p-md-0">
                <span class="logo">NebulaNarratives</span>
            </div>
            
            <!-- Search bar when screen is wider than 768px -->
            <div class="">
                <form action="{{url_for('main.search')}}" class="d-flex me-3 d-none d-md-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                    <button type="button" class="btn btn-secondary" type="submit"><i class="bi bi-search"></i></button>
                </form>
            </div>
            
            <!-- Offcanvas for small screens -->
            <button class="btn btn-secondary d-md-none ms-auto me-3" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasResponsive" aria-controls="offcanvasResponsive">
                <i class="bi bi-border-width"></i>
            </button>
            <div class="offcanvas-md d-md-none offcanvas-end ms-auto" tabindex="-1" id="offcanvasResponsive" aria-labelledby="offcanvasResponsiveLabel">
                <div class="offcanvas-header">
                    <h3 class="offcanvas-title" id="offcanvasResponsiveLabel">Menu</h3>
                    <button type="button" class="btn-close btn-light" data-bs-dismiss="offcanvas" data-bs-target="#offcanvasResponsive" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.comics') }}">Comics</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <hr class="">
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.account') }}">
                                <i class="bi bi-gear"></i>   Account settings 
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.wishlist') }}">
                                <i class="bi bi-heart-fill"></i>  Wishlist
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{{ url_for('users.cart') }}">
                                <i class="bi bi-cart4"></i>  Cart
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.library') }}">
                                <i class="bi bi-book-fill"></i>  Library
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.report') }}">
                                <i class="bi bi-book-fill"></i>  Report Product
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.report_income') }}">
                                <i class="bi bi-book-fill"></i>  Report Income
                                </a>
                            </li>
                            <hr class="section-divider">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('users.logout') }}">
                                Logout
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{{ url_for('users.login') }}">Login</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('users.signup') }}">Sign up</a>
                            </li>
                        {% endif %}

                        <!-- Search bar for the offcanvas -->
                        <form action="{{url_for('main.search')}}" class="d-flex mt-5" role="search">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                            <button class="btn btn-secondary" type="submit"><i class="bi bi-search"></i></button>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <!-- The links navbar -->
    <ul class="nav nav-links justify-content-center d-none d-md-flex">
        <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.comics') }}">Comics</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        </li>
    </ul>

    <!-- Main -->
    <main>
        <!-- Flash messages display here -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="container-fluid" id="flash" >
                {% for category, message in messages %}
                <div class=" msg alert alert-{{ category }}">
                    {{ message }}
                    <button type="button" class="close btn ms-auto"><i><i class="bi bi-x-lg ms-auto"></i></i></button>
                </div>
                <br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}

        <!-- Main content -->
        {% block content %}
        {% endblock %}
    </main>

    <!-- Footer -->
    <footer>
        <nav>
            <div class="container mt-2 mt-md-0 ms-auto me-auto pb-4 pt-4 row row-cols-1 row-cols-md-4 text-center" style="max-width: 1048px;">
                <div class="col" style="min-height: 100px; margin: auto; align-self: center;">
                   <span class="logo mt-auto mb-auto">NebulaNarratives</span>
                </div>
                <div class="col mt-md-0 mt-3 mb-3">
                    <h4 class="h4">About us</h4>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.about') }}#who-are-we">Who are we</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.about') }}#team">The team</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.about') }}">Where we are</a>
                        </li>
                    </ul>
                </div>
                <div class="col mt-md-0 mt-3">
                    <h4 class="h4">Contact us</h4>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Email us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Call us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Send a complaint</a>
                        </li>
                    </ul>
                </div>
                <div class="col mt-md-0 mt-3">
                    <h4 class="h4">Socials</h4>
                    <ul class="social-links">
                        <li class="">
                            <a href="#"><img src="static/images/icons/instagram_icon.png" alt="instagram link"></a>
                        </li>
                        <li class="">
                            <a href="#"><img src="static/images/icons/twitter_icon.png" alt="twitter link"></a>
                        </li>
                        <li class="">
                            <a href="#"><img src="static/images/icons/youtube_icon.png" alt="youtube link"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </footer>
    <script>
        document.querySelector('.close').addEventListener('click', (e) => {
            document.querySelector('#flash').style.display = 'none'
        })
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

mysite/website/templates/secondary_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block styles %}{% endblock %}
    <title>NebulaNarratives | {{ title }}</title>
</head>
<body>
    <!-- Main -->
    <main>
        <!-- Flash messages display here -->
        <div class="container-md flash-message">
            <div class="">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} ms-auto me-auto col-md-8 mt-4 mb-4"> {{ message }}</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>

        <!-- Main content -->
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>